# Generated by Django 5.0.6 on 2024-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Результат попытки"
            ),
        ),
    ]
